name = "DFTranspose"
uuid = "97ed5823-4806-477e-8be3-be3e0d6ee308"
authors = ["sl-solution <github.sl.solution@icloud.com> and contributors"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
